name: Build project using muddler and upload artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Muddle
        uses: demonnic/build-with-muddler@main
        with:
          muddlerVersion: 0.5
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Soiken
          path: build/
          
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: Soiken
          path: downloaded-artifact

      - name: Print Current Directory
        run: pwd

      - name: Print Workspace Directory
        run: echo ${{ github.workspace }}
      
      - name: List Files in Workspace
        run: ls -R ${{ github.workspace }}

      - name: Debug Step
        run: |
          echo "GitHub Workspace: ${{ github.workspace }}"
          echo "Target Folder: $GITHUB_WORKSPACE/build"
          echo "Repository Path: $GITHUB_REPOSITORY"
          echo "Location: $(pwd)"
          ls -R ${{ github.workspace }}/downloaded-artifact
        env:
          MUDDLER_VERSION: 0.5
      
      - name: Move Artifact to Repository Folder
        run: cp -r ${{ github.workspace }}/downloaded-artifact/* $GITHUB_WORKSPACE/build/
        env:
          MUDDLER_VERSION: 0.5



