name: Build project using muddler and upload artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Muddle
        uses: demonnic/build-with-muddler@main
        with:
          muddlerVersion: 0.5
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Soiken
          path: build/
          
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: Soiken
          path: downloaded-artifact

      - name: Move Artifact to Repository Folder
        run: cp -r downloaded-artifact/* build/
