name: Build project using muddler and upload artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Muddle
        uses: demonnic/build-with-muddler@master
      
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: Soiken
          path: build/tmp/
