name: Build project using muddler and upload artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Muddle
        uses: demonnic/build-with-muddler@main
        with:
          muddlerVersion: 1.0.3
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3
        with:
          name: Soiken
          path: build/tmp/
