name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Change working directory to main/Scripts/Soiken
        run: cd main/Scripts/Soiken

      - name: Muddle
        uses: demonnic/build-with-muddler@v1.3

      - name: Upload MPackage
        uses: actions/upload-artifact@v3.1.2
        with:
          name: MDK-package
          path: build/tmp/

      - name: Run Busted tests
        uses: demonnic/test-in-mudlet@v1.2
        with:
          pretestPackage: ${{ github.workspace }}/build/MDK.mpackage
