name: Build with Muddler

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Change working directory
      run: cd main/Scripts/Soiken

    - name: Build with Muddler
      run: |
        # Run your Muddler commands here, e.g., muddler build
        # Replace the following command with your actual Muddler build command
        muddler build
